import { message } from "antd";
import { saveAs } from "file-saver";
import { toBlob } from "html-to-image";
import { makeAutoObservable } from "mobx";
import { openExportPDFHelp } from "src/components/popups/exportPDF";
import { router } from "src/router";
import { toEditor } from "./route";
import { appStore } from "src/stores/app";
import { showInfo } from "src/shared/toast";
